export enum StatusItem {
  AVAILABLE = 'AVAILABLE',
  EXCHANGED = 'EXCHANGED',
  EXPIRED = 'EXPIRED',
  IN_EXCHANGE = 'IN_EXCHANGE',
  NO_LONGER_FOR_EXCHANGE = 'NO_LONGER_FOR_EXCHANGE',
  PENDING = 'PENDING',
  REJECTED = 'REJECTED',
}
